### ISSUE TITLE
Error in SBML parsing: `tried to add a local symbol Cve_icg with value Cve_icg, but Cve_icg was already instantiated`

### ISSUE THREAD

**Issue by matthiaskoenig** [AMICI-dev/AMICI#1779]
Tried to parse the attached model with the latest development version of AMICI and petab in python but the SBML import fails due to 
```
amici.sbml_import.SBMLException: AMICI tried to add a local symbol Cve_icg with value Cve_icg, but Cve_icg was already instantiated with Cve_icg. This means that there are multiple SBML elements with SId Cve_icg, which is invalid SBML. This can be fixed by renaming the elements with SId Cve_icg.
```
Model is valid SBML, so most likely a bug in AMICI SBML parsing.

Model:
[icg_v1.zip](https://github.com/AMICI-dev/AMICI/files/8455549/icg_v1.zip)

```
from pathlib import Path

import petab
import amici.petab_import
import numpy as np
import matplotlib.pyplot as plt
from amici.petab_import import import_petab_problem


output_dir: Path = Path(__file__).parent / "results" / "icg"
yaml_file: Path = output_dir / "icg.yaml"

# ---------------------------------------------------------------------------------------------------------------------
# Setup
# ---------------------------------------------------------------------------------------------------------------------
# Import yaml
petab_problem = petab.Problem.from_yaml(yaml_file)

# compile the petab problem to an AMICI ODE model
amici_model = amici.petab_import.import_petab_problem(petab_problem)

# Import PEtab problem to amici
amici_model = import_petab_problem(petab_problem)
```
results in
```
2022-04-09 00:11:00.142 - amici.petab_import - INFO - Importing model ...
2022-04-09 00:11:00.143 - amici.petab_import - INFO - Model name is 'icg_body'.
Writing model code to '/home/mkoenig/git/pkdb_models/pkdb_models/models/icg/fit_petab/amici_models/icg_body'.
2022-04-09 00:11:00.145 - amici.petab_import - INFO - Species: 12
2022-04-09 00:11:00.145 - amici.petab_import - INFO - Global parameters: 75
2022-04-09 00:11:00.145 - amici.petab_import - INFO - Reactions: 16
2022-04-09 00:11:00.199 - amici.petab_import - INFO - Observables: 5
2022-04-09 00:11:00.199 - amici.petab_import - INFO - Sigmas: 5
2022-04-09 00:11:00.204 - amici.petab_import - DEBUG - Adding output parameters to model: OrderedDict([('noiseParameter1_Cve_icg', None), ('noiseParameter1_Chv_icg', None), ('noiseParameter1_Car_icg', None), ('noiseParameter1_ER_icg', None), ('noiseParameter1_LI__ICGLI2BI', None)])
2022-04-09 00:11:00.204 - amici.petab_import - DEBUG - Adding preequilibration indicator constant preequilibration_indicator
2022-04-09 00:11:00.204 - amici.petab_import - DEBUG - Adding initial assignments for ['IVDOSE_icg']
2022-04-09 00:11:00.204 - amici.petab_import - DEBUG - Condition table: (16, 5)
2022-04-09 00:11:00.205 - amici.petab_import - DEBUG - Fixed parameters are ['preequilibration_indicator', 'BW', 'Ri_icg']
2022-04-09 00:11:00.205 - amici.petab_import - INFO - Overall fixed parameters: 3
2022-04-09 00:11:00.205 - amici.petab_import - INFO - Variable parameters: 80
2022-04-09 00:11:00.267 - amici.sbml_import - INFO - Finished gathering local SBML symbols       ++ (6.12E-02s)
2022-04-09 00:11:00.315 - amici.sbml_import - INFO - Finished processing SBML parameters         ++ (4.79E-02s)
2022-04-09 00:11:00.316 - amici.sbml_import - INFO - Finished processing SBML compartments       ++ (1.10E-03s)
2022-04-09 00:11:00.318 - amici.sbml_import - INFO - Finished processing SBML species initials  +++ (1.38E-03s)
2022-04-09 00:11:00.322 - amici.sbml_import - INFO - Finished processing SBML rate rules        +++ (3.19E-03s)
2022-04-09 00:11:00.322 - amici.sbml_import - INFO - Finished processing SBML species            ++ (5.37E-03s)
2022-04-09 00:11:00.328 - amici.sbml_import - INFO - Finished processing SBML reactions          ++ (5.74E-03s)
2022-04-09 00:11:00.385 - amici.sbml_import - INFO - Finished processing SBML rules              ++ (5.71E-02s)
2022-04-09 00:11:00.385 - amici.sbml_import - INFO - Finished processing SBML initial assignments++ (1.26E-04s)
2022-04-09 00:11:00.387 - amici.sbml_import - INFO - Finished processing SBML species references ++ (1.56E-03s)
2022-04-09 00:11:00.387 - amici.sbml_import - INFO - Finished processing SBML events             ++ (1.43E-04s)
2022-04-09 00:11:00.387 - amici.sbml_import - INFO - Finished importing SBML                      + (1.82E-01s)
Traceback (most recent call last):
  File "/home/mkoenig/git/pkdb_models/pkdb_models/models/icg/fit_petab/icg_amici.py", line 37, in <module>
    amici_model = amici.petab_import.import_petab_problem(petab_problem)
  File "/home/mkoenig/git/AMICI/python/sdist/amici/petab_import.py", line 307, in import_petab_problem
    import_model_sbml(
  File "/home/mkoenig/git/AMICI/python/sdist/amici/logging.py", line 194, in wrapper_timer
    rval = func(*args, **kwargs)
  File "/home/mkoenig/git/AMICI/python/sdist/amici/petab_import.py", line 577, in import_model_sbml
    sbml_importer.sbml2amici(
  File "/home/mkoenig/git/AMICI/python/sdist/amici/sbml_import.py", line 342, in sbml2amici
    self._process_observables(observables, sigmas, noise_distributions)
  File "/home/mkoenig/git/AMICI/python/sdist/amici/logging.py", line 194, in wrapper_timer
    rval = func(*args, **kwargs)
  File "/home/mkoenig/git/AMICI/python/sdist/amici/sbml_import.py", line 1198, in _process_observables
    self.add_local_symbol(obs, symbol_with_assumptions(obs))
  File "/home/mkoenig/git/AMICI/python/sdist/amici/sbml_import.py", line 594, in add_local_symbol
    raise SBMLException(
amici.sbml_import.SBMLException: AMICI tried to add a local symbol Cve_icg with value Cve_icg, but Cve_icg was already instantiated with Cve_icg. This means that there are multiple SBML elements with SId Cve_icg, which is invalid SBML. This can be fixed by renaming the elements with SId Cve_icg.
```

**Comment by dweindl** [comment]
Hi Matthias, the SBML model is valid, but the PEtab files are not. The model defines a species with ID `Cve_icg` and in `icg_observable.tsv` you defined an observable with the same ID. This is not allowed. Renaming the observable should fix this. (untested).

Unrelated to this error: Condition IDs must not contain `.`.

**Comment by matthiaskoenig** [comment]
Perfect. Thanks. Just getting up to speed with PEtab. Closing this after fixing my PEtab files.
