### ISSUE TITLE
 ModuleNotFoundError: No module named 'setuptools.command.build'

### ISSUE THREAD

**Issue by cerdem12** [AMICI-dev/AMICI#1883]
Hey Daniel,
I was trying to create a docker image using AMICI==0.11.12 on a Ubuntu 22.04.1 LTS machine.
I get the error:

HDF5 library found. Building AMICI with HDF5 support.
    running egg_info
    creating pip-egg-info/amici.egg-info
    writing pip-egg-info/amici.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/amici.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/amici.egg-info/entry_points.txt
    writing requirements to pip-egg-info/amici.egg-info/requires.txt
    writing top-level names to pip-egg-info/amici.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/amici.egg-info/SOURCES.txt'
    /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ukx8ag7s/amici/setup.py", line 244, in <module>
        main()
      File "/tmp/pip-build-ukx8ag7s/amici/setup.py", line 238, in main
        'Topic :: Scientific/Engineering :: Bio-Informatics',
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 278, in run
        self.find_sources()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 293, in find_sources
        mm.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 524, in run
        self.add_defaults()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 560, in add_defaults
        sdist.add_defaults(self)
      File "/usr/lib/python3/dist-packages/setuptools/command/py36compat.py", line 34, in add_defaults
        self._add_defaults_python()
      File "/usr/lib/python3/dist-packages/setuptools/command/sdist.py", line 127, in _add_defaults_python
        build_py = self.get_finalized_command('build_py')
      File "/usr/lib/python3.6/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/command/build_py.py", line 34, in finalize_options
        orig.build_py.finalize_options(self)
      File "/usr/lib/python3.6/distutils/command/build_py.py", line 45, in finalize_options
        ('force', 'force'))
      File "/usr/lib/python3.6/distutils/cmd.py", line 286, in set_undefined_options
        src_cmd_obj = self.distribution.get_command_obj(src_cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 846, in get_command_obj
        klass = self.get_command_class(command)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 634, in get_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
        return self.resolve()
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ModuleNotFoundError: No module named 'setuptools.command.build'

I saw the issue fixed for an earlier version but it did pop-up for me now. Any suggestions?

**Comment by dweindl** [comment]
Hi Cemal, I don't seem to be able to reproduce this with the current version of `setuptools` (65.5.1). Could you try upgrading (`pip install -U setuptools`) and see if the problem persists? Unless you specifically need AMICI==0.11.12, I would also suggest to use a more recent version, there have been a couple of improvements.

**Comment by cerdem12** [comment]
Trying that now. According to my lab-mate, we need to use the 0.11.12 version for now, because of something with "observables". We can talk about that later in another issue :D

**Comment by cerdem12** [comment]
FYI, I am trying: https://github.com/birtwistlelab/SPARCED/blob/master/docker/jupyter.Dockerfile

**Comment by dweindl** [comment]
Hi Cemal, I don't really know what the problem is, but it is something outside AMICI. `python3 -m pip install --upgrade pip setuptools wheel` resolved it. Had to install libsbml with `pip install python-libsbml --only-binary python-libsbml` (again unrelated to amici).
