### ISSUE TITLE
Support execution of SBML comp models

### ISSUE THREAD

**Issue by matthiaskoenig** [AMICI-dev/AMICI#2061]
Currently, AMICI raises an error if the `comp` package appears in models. This should be a warning or there should be an option to force execution with comp. Similar things for the `fbc` package. See example attached which is a completely fine model which can be simulated with roadrunner and copasi, but AMICI complains about it. 

Trying to load the attached `liver_model.xml` 
[icg_liver.zip](https://github.com/AMICI-dev/AMICI/files/11337537/icg_liver.zip)
results in 
```
Traceback (most recent call last):
  File "/home/mkoenig/git/sbmlsim/src/sbmlsim/comparison/example_comparison.py", line 82, in <module>
    simulator = simulator(
  File "/home/mkoenig/git/sbmlsim/src/sbmlsim/comparison/simulate_amici.py", line 31, in __init__
    sbml_importer.sbml2amici(self.mid, model_dir)
  File "/home/mkoenig/.virtualenvs/sbmlsim/lib/python3.9/site-packages/amici/sbml_import.py", line 344, in sbml2amici
    ode_model = self._build_ode_model(
  File "/home/mkoenig/.virtualenvs/sbmlsim/lib/python3.9/site-packages/amici/sbml_import.py", line 416, in _build_ode_model
    self._process_sbml(constant_parameters)
  File "/home/mkoenig/.virtualenvs/sbmlsim/lib/python3.9/site-packages/amici/logging.py", line 199, in wrapper_timer
    rval = func(*args, **kwargs)
  File "/home/mkoenig/.virtualenvs/sbmlsim/lib/python3.9/site-packages/amici/sbml_import.py", line 457, in _process_sbml
    self.check_support()
  File "/home/mkoenig/.virtualenvs/sbmlsim/lib/python3.9/site-packages/amici/sbml_import.py", line 495, in check_support
    raise SBMLException(
amici.sbml_import.SBMLException: Required SBML extension comp is currently not supported!
```

Many comp models can still be simulated, often correctly. Just because the comp package appears in a model does not mean it is not a valid and simulatable model with the SBML core. E.g. comp ports are often used as annotation of interfaces, but do not change the model ODE system.

You could also just call the SBML flattening on the comp model, which is a one-liner in libsbml which converts the model to a valid core model. This is how roadrunner (and I think also COPASI) support comp models. I.e. they detect if the comp package is there (what you already are doing) and flatten the model before execution (this is missing).

**Comment by matthiaskoenig** [comment]
Basically you just have to do the following on the SBMLDocument:
```python
    props = libsbml.ConversionProperties()
    props.addOption("flatten comp", True)  # Invokes CompFlatteningConverter
    props.addOption("leave_ports", False)  # Indicates whether to leave ports
    props.addOption("abortIfUnflattenable", "none")

    # flatten
    current = time.perf_counter()
    result = doc.convert(props)
    flattened_status = result == libsbml.LIBSBML_OPERATION_SUCCESS
```

**Comment by dweindl** [comment]
Thanks, will add it.

**Comment by dweindl** [comment]
This requires fixing some additional issues in #2063, #2064. Won't be able to do that during the next week, but will try to look into that thereafter.

**Comment by dweindl** [comment]
That should work now on branch `develop`. For `fbc`, only extra attributes to core elements are supported, but no additional fbc elements.

**Comment by matthiaskoenig** [comment]
This is perfect. Just tested and works. Can be closed from my side. Thanks a lot.
