### ISSUE TITLE
Amici installation with hdf5 support in conda env

### ISSUE THREAD

**Issue by shoepfl** [AMICI-dev/AMICI#2141]
Hi,

amici installation with hdf5 support does not work for me any more.

I try to install amici in an conda virtual environmen.
Installation without hdf5 support works perfectly, however if I try to install amici after having hdf5 installed I get the following error:

Building wheel for amici (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for amici (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [194 lines of output]
      running AmiciInstall
      running bdist_wheel
      running build
      running build_py
      running AmiciBuildPy
      running build_ext
      ------------------------------ SuiteSparse_config ------------------------------
      -- Building SuiteSparse_config version: v7.0.1 (Jan 20, 2023)
      -- Source:        /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/amici/ThirdParty/SuiteSparse/SuiteSparse_config
      -- Build:         /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/temp.linux-x86_64-cpython-310_SuiteSparse_config
      -- The C compiler identification is GNU 13.1.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /home/st/st_us-030810/st_st142030/.conda/envs/eulerpi_hdf5/bin/x86_64-conda-linux-gnu-cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Install lib:     lib64
      -- Install include: include
      -- Install bin:     bin
      -- Install rpath:
      -- Build   rpath:   /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/temp.linux-x86_64-cpython-310_SuiteSparse_config
      -- Build type:    Release
      -- Fortran: not enabled
      -- CUDA: not enabled
      -- Found OpenMP_C: -fopenmp (found version "4.5")
      -- Found OpenMP: TRUE (found version "4.5")
      -- OpenMP C libraries:      /home/st/st_us-030810/st_st142030/.conda/envs/eulerpi_hdf5/lib/libgomp.so;/pfs/data5/home/st/st_us-030810/st_st142030/.conda/envs/eulerpi_hdf5/x86_64-conda-linux-gnu/sysroot/usr/lib/libpthread.so
      -- OpenMP C include:
      -- OpenMP C flags:          -fopenmp
      -- ------------------------------------------------------------------------
      -- SuiteSparse CMAKE report for: suitesparseconfig
      -- ------------------------------------------------------------------------
      -- inside common SuiteSparse root:  false
      -- install in SuiteSparse/lib and SuiteSparse/include: OFF
      -- build type:           Release
      -- NSTATIC:              false (build static library)
      -- use OpenMP:           yes
      -- C compiler:           /home/st/st_us-030810/st_st142030/.conda/envs/eulerpi_hdf5/bin/x86_64-conda-linux-gnu-cc
      -- C flags:              -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/st/st_us-030810/st_st142030/.conda/envs/eulerpi_hdf5/include -fopenmp
      -- C++ compiler:
      -- C++ flags:
      -- C Flags release:      -O3 -DNDEBUG
      -- C++ Flags release:
      -- Fortran compiler:     none
      -- compile definitions:
      -- BLAS integer:         int64_t
      -- ------------------------------------------------------------------------
      -- Configuring done (0.9s)
      -- Generating done (0.0s)
      CMake Warning:
        Manually-specified variables were not used by the project:
      
          BLA_VENDOR
      
      
      -- Build files have been written to: /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/temp.linux-x86_64-cpython-310_SuiteSparse_config
      [1/5] /home/st/st_us-030810/st_st142030/.conda/envs/eulerpi_hdf5/bin/x86_64-conda-linux-gnu-cc -Dsuitesparseconfig_EXPORTS -I/scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/temp.linux-x86_64-cpython-310_SuiteSparse_config -I/scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/amici/ThirdParty/SuiteSparse/SuiteSparse_config -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/st/st_us-030810/st_st142030/.conda/envs/eulerpi_hdf5/include -fopenmp  -O3 -DNDEBUG -fPIC -MD -MT CMakeFiles/suitesparseconfig.dir/SuiteSparse_config.c.o -MF CMakeFiles/suitesparseconfig.dir/SuiteSparse_config.c.o.d -o CMakeFiles/suitesparseconfig.dir/SuiteSparse_config.c.o -c /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/amici/ThirdParty/SuiteSparse/SuiteSparse_config/SuiteSparse_config.c
      [2/5] : && /home/st/st_us-030810/st_st142030/.conda/envs/eulerpi_hdf5/bin/x86_64-conda-linux-gnu-cc -fPIC -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/st/st_us-030810/st_st142030/.conda/envs/eulerpi_hdf5/include -fopenmp  -O3 -DNDEBUG  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/home/st/st_us-030810/st_st142030/.conda/envs/eulerpi_hdf5/lib -Wl,-rpath-link,/home/st/st_us-030810/st_st142030/.conda/envs/eulerpi_hdf5/lib -L/home/st/st_us-030810/st_st142030/.conda/envs/eulerpi_hdf5/lib -shared -Wl,-soname,libsuitesparseconfig.so.7 -o libsuitesparseconfig.so.7.0.1 CMakeFiles/suitesparseconfig.dir/SuiteSparse_config.c.o  -Wl,-rpath,/scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/temp.linux-x86_64-cpython-310_SuiteSparse_config:  -lm  /home/st/st_us-030810/st_st142030/.conda/envs/eulerpi_hdf5/lib/libgomp.so  -lpthread && :
      [3/5] /scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake -E cmake_symlink_library libsuitesparseconfig.so.7.0.1  libsuitesparseconfig.so.7 libsuitesparseconfig.so && :
      [4/5] /home/st/st_us-030810/st_st142030/.conda/envs/eulerpi_hdf5/bin/x86_64-conda-linux-gnu-cc  -I/scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/temp.linux-x86_64-cpython-310_SuiteSparse_config -I/scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/amici/ThirdParty/SuiteSparse/SuiteSparse_config -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/st/st_us-030810/st_st142030/.conda/envs/eulerpi_hdf5/include -fopenmp  -O3 -DNDEBUG -fPIC -MD -MT CMakeFiles/suitesparseconfig_static.dir/SuiteSparse_config.c.o -MF CMakeFiles/suitesparseconfig_static.dir/SuiteSparse_config.c.o.d -o CMakeFiles/suitesparseconfig_static.dir/SuiteSparse_config.c.o -c /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/amici/ThirdParty/SuiteSparse/SuiteSparse_config/SuiteSparse_config.c
      [5/5] : && /scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake -E rm -f libsuitesparseconfig.a && /home/st/st_us-030810/st_st142030/.conda/envs/eulerpi_hdf5/bin/x86_64-conda-linux-gnu-ar qc libsuitesparseconfig.a  CMakeFiles/suitesparseconfig_static.dir/SuiteSparse_config.c.o && /home/st/st_us-030810/st_st142030/.conda/envs/eulerpi_hdf5/bin/x86_64-conda-linux-gnu-ranlib libsuitesparseconfig.a && :
      -- Install configuration: "Release"
      -- Installing: /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/lib.linux-x86_64-cpython-310/amici/lib64/libsuitesparseconfig.so.7.0.1
      -- Installing: /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/lib.linux-x86_64-cpython-310/amici/lib64/libsuitesparseconfig.so.7
      -- Set runtime path of "/scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/lib.linux-x86_64-cpython-310/amici/lib64/libsuitesparseconfig.so.7.0.1" to ""
      -- Installing: /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/lib.linux-x86_64-cpython-310/amici/lib64/libsuitesparseconfig.so
      -- Installing: /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/lib.linux-x86_64-cpython-310/amici/include/SuiteSparse_config.h
      -- Installing: /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/lib.linux-x86_64-cpython-310/amici/lib64/cmake/SuiteSparse/FindSuiteSparse_config.cmake
      -- Installing: /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/lib.linux-x86_64-cpython-310/amici/lib64/cmake/SuiteSparse/SuiteSparseBLAS.cmake
      -- Installing: /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/lib.linux-x86_64-cpython-310/amici/lib64/cmake/SuiteSparse/SuiteSparseBLAS32.cmake
      -- Installing: /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/lib.linux-x86_64-cpython-310/amici/lib64/cmake/SuiteSparse/SuiteSparseBLAS64.cmake
      -- Installing: /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/lib.linux-x86_64-cpython-310/amici/lib64/cmake/SuiteSparse/SuiteSparseLAPACK.cmake
      -- Installing: /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/lib.linux-x86_64-cpython-310/amici/lib64/cmake/SuiteSparse/SuiteSparsePolicy.cmake
      -- Installing: /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/lib.linux-x86_64-cpython-310/amici/lib64/cmake/SuiteSparse/SuiteSparseReport.cmake
      -- Installing: /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/lib.linux-x86_64-cpython-310/amici/lib64/cmake/SuiteSparse/SuiteSparse_ssize_t.cmake
      -- Installing: /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/lib.linux-x86_64-cpython-310/amici/lib64/libsuitesparseconfig.a
      ------------------------------ SuiteSparse_config ------------------------------
      ------------------------------ amd ------------------------------
      -- Building AMD version: v3.0.3 (Jan 17, 2023)
      -- Source:        /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/amici/ThirdParty/SuiteSparse/AMD
      -- Build:         /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/temp.linux-x86_64-cpython-310_amd
      -- The C compiler identification is GNU 13.1.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /home/st/st_us-030810/st_st142030/.conda/envs/eulerpi_hdf5/bin/x86_64-conda-linux-gnu-cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Install lib:     lib64
      -- Install include: include
      -- Install bin:     bin
      -- Install rpath:
      -- Build   rpath:   /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/temp.linux-x86_64-cpython-310_amd
      -- Build type:    Release
      -- Fortran: not enabled
      -- CUDA: not enabled
      -- original library suffixes: .so;.a
      -- revised for static search: .a;.so;.a
      CMake Error at /scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find SuiteSparse_config: Found unsuitable version "4.4.4", but
        required is at least "7.0.0" (found
        /usr/lib64/libsuitesparseconfig.so.4.4.4)
      
            Reason given by package: result
      
      Call Stack (most recent call first):
        /scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:598 (_FPHSA_FAILURE_MESSAGE)
        /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/amici/ThirdParty/SuiteSparse/SuiteSparse_config/cmake_modules/FindSuiteSparse_config.cmake:114 (find_package_handle_standard_args)
        CMakeLists.txt:60 (find_package)
      
      
      -- Configuring incomplete, errors occurred!
      running AmiciBuildCMakeExtension
      
      ==> Configuring:
      $ cmake -S /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/amici/ThirdParty/SuiteSparse/SuiteSparse_config -B /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/temp.linux-x86_64-cpython-310_SuiteSparse_config -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/lib.linux-x86_64-cpython-310/amici -DCMAKE_MAKE_PROGRAM=/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/bin/ninja -DCMAKE_VERBOSE_MAKEFILE=ON -DBLA_VENDOR=All -DENABLE_CUDA=FALSE -DNFORTRAN=TRUE
      
      ==> Building:
      $ cmake --build /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/temp.linux-x86_64-cpython-310_SuiteSparse_config --config Release
      
      ==> Installing:
      $ cmake --install /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/temp.linux-x86_64-cpython-310_SuiteSparse_config
      
      
      ==> Configuring:
      $ cmake -S /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/amici/ThirdParty/SuiteSparse/AMD -B /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/temp.linux-x86_64-cpython-310_amd -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/lib.linux-x86_64-cpython-310/amici -DCMAKE_MAKE_PROGRAM=/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/bin/ninja -DCMAKE_VERBOSE_MAKEFILE=ON -DNFORTRAN=TRUE
      
      ==> Building:
      $ cmake --build /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/temp.linux-x86_64-cpython-310_amd --config Release
      
      ==> Installing:
      $ cmake --install /scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/temp.linux-x86_64-cpython-310_amd
      
      Traceback (most recent call last):
        File "/home/st/st_us-030810/st_st142030/.conda/envs/eulerpi_hdf5/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/st/st_us-030810/st_st142030/.conda/envs/eulerpi_hdf5/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/st/st_us-030810/st_st142030/.conda/envs/eulerpi_hdf5/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 175, in <module>
        File "<string>", line 159, in main
        File "/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/amici/custom_commands.py", line 124, in run
          self.run_command("build_ext")
        File "/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/amici/custom_commands.py", line 150, in run
          result = super().run()
        File "/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/cmake_build_extension/build_extension.py", line 113, in run
          self.build_extension(ext)
        File "/scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/amici/custom_commands.py", line 177, in build_extension
          super().build_extension(ext)
        File "/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/lib/python3.10/site-packages/cmake_build_extension/build_extension.py", line 229, in build_extension
          subprocess.check_call(configure_command)
        File "/home/st/st_us-030810/st_st142030/.conda/envs/eulerpi_hdf5/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '-S', '/scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/amici/ThirdParty/SuiteSparse/AMD', '-B', '/scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/temp.linux-x86_64-cpython-310_amd', '-GNinja', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX:PATH=/scratch/slurm_tmpdir/job_22408247/pip-install-vnt46sf4/amici_5ee2ee206f184a8ba9a820a83be4db06/build/lib.linux-x86_64-cpython-310/amici', '-DCMAKE_MAKE_PROGRAM=/scratch/slurm_tmpdir/job_22408247/pip-build-env-ivcijiwz/overlay/bin/ninja', '-DCMAKE_VERBOSE_MAKEFILE=ON', '-DNFORTRAN=TRUE']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for amici
Failed to build amici
ERROR: Could not build wheels for amici, which is required to install pyproject.toml-based projects

hdf is installed via `conda install hdf5`
I tried it on a JupyterLab (hosted by the BWUniCluster and on my WSL with Ubuntu 20.04).

Thanks for any advice

**Comment by dweindl** [comment]
Hi @shoepfl, could please share the full installation log (`pip install -v [...]`) for the successful installation as well as the commands you are using for either installation?

**Comment by shoepfl** [comment]
Hi @dweindl,

of course, it now seems that the installation has worked.
My commands for installtion with hdf5 support were:

`conda create -n test python=3.10`
`conda activate test`

`conda install gcc_linux-64 gxx_linux-64 swig blas libopenblas`
`conda install -c conda-forge blas openblas`

`export CONDA_DIR=$CONDA_PREFIX`

`conda install pip`

`conda install hdf5`

`pip install -v --no-cache amici`

You can find the full installation log attached. [amici_hdf5_installation_log.txt](https://github.com/AMICI-dev/AMICI/files/11998828/amici_hdf5_installation_log.txt)


However, I get an error by executing my skript:

Testing SWIG executable swig4.0... SUCCEEDED.
error: command '/home/basti/miniconda3/envs/amici_hdf5_test/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1

Failed building the model extension.
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/basti/miniconda3/envs/amici_hdf5_test/bin/python', '/mnt/c/Users/basti/Documents/Uni/11_Doktorarbeit/Project_MRI/EPI/amici/SBMLModel/setup.py', '--quiet', 'build_ext', '--build-lib=/mnt/c/Users/basti/Documents/Uni/11_Doktorarbeit/Project_MRI/EPI/amici/SBMLModel']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/basti/miniconda3/envs/amici_hdf5_test/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/basti/miniconda3/envs/amici_hdf5_test/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/basti/miniconda3/envs/amici_hdf5_test/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/basti/miniconda3/envs/amici_hdf5_test/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/basti/miniconda3/envs/amici_hdf5_test/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/basti/miniconda3/envs/amici_hdf5_test/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/basti/miniconda3/envs/amici_hdf5_test/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/basti/Documents/Uni/11_Doktorarbeit/Project_MRI/EPI/EPI_PVL_perfusion.py", line 18, in <module>
    model = SBMLModel('rtd_pvl_perfusion_identical_response_times.xml',
  File "/home/basti/miniconda3/envs/amici_hdf5_test/lib/python3.10/site-packages/eulerpi/core/model.py", line 325, in __init__
    sbml_importer.sbml2amici(
  File "/home/basti/miniconda3/envs/amici_hdf5_test/lib/python3.10/site-packages/amici/sbml_import.py", line 375, in sbml2amici
    exporter.compile_model()
  File "/home/basti/miniconda3/envs/amici_hdf5_test/lib/python3.10/site-packages/amici/logging.py", line 199, in wrapper_timer
    rval = func(*args, **kwargs)
  File "/home/basti/miniconda3/envs/amici_hdf5_test/lib/python3.10/site-packages/amici/ode_export.py", line 2463, in compile_model
    self._compile_c_code(compiler=self.compiler,
  File "/home/basti/miniconda3/envs/amici_hdf5_test/lib/python3.10/site-packages/amici/ode_export.py", line 2547, in _compile_c_code
Deprecated command line option: -modern. This option is now always on.
Jy.cpp:8:10: fatal error: p.h: No such file or directory
    8 | #include "p.h"
      |          ^~~~~
compilation terminated.
running AmiciInstall
Adding OpenMP flags...
hdf5.h found in /home/basti/miniconda3/envs/amici_hdf5_test/include
libhdf5.a found in /home/basti/miniconda3/envs/amici_hdf5_test/lib
Changed extra_compile_args for unix to ['-fopenmp', '-std=c++14']
Building model extension in /mnt/c/Users/basti/Documents/Uni/11_Doktorarbeit/Project_MRI/EPI/amici/SBMLModel
Testing SWIG executable swig4.0... SUCCEEDED.
error: command '/home/basti/miniconda3/envs/amici_hdf5_test/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1

I have to say that I currently try to include amici in the eulerpi (for estimation of parameter distributions according to observed data) toolbox for SBML support. So the problem might also lie on my side an I will now look deeper into this. If you have any spontanous idea what the problem could be, it would be of course very helpful anyway.
