### ISSUE TITLE
`ERROR setuptools_scm._integration.setuptools pyproject.toml does not contain a tool.setuptools_scm section`

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#2177]
When installing AMICI, e.g. https://github.com/AMICI-dev/AMICI/actions/runs/6281697506/job/17060375804

See also https://github.com/apache/arrow/issues/37803

```
  Successfully installed GitPython-3.1.37 cmake-3.27.5 cmake-build-extension-0.5.1 gitdb-4.0.10 ninja-1.11.1 numpy-1.19.3 oldest-supported-numpy-2023.8.3 packaging-23.1 setuptools-68.2.2 setuptools-scm-8.0.3 smmap-5.0.1 tomli-2.0.1 typing-extensions-4.8.0 wheel-0.41.2
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Running command Getting requirements to build wheel
  ERROR setuptools_scm._integration.setuptools pyproject.toml does not contain a tool.setuptools_scm section
  Traceback (most recent call last):
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qflslxot\overlay\Lib\site-packages\setuptools_scm\_integration\pyproject_reading.py", line 53, in read_pyproject
      section = defn.get("tool", {})[tool_name]
  KeyError: 'setuptools_scm'

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qflslxot\overlay\Lib\site-packages\setuptools_scm\_integration\setuptools.py", line 121, in infer_version
      config = _config.Configuration.from_file(dist_name=dist_name)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qflslxot\overlay\Lib\site-packages\setuptools_scm\_config.py", line 128, in from_file
      pyproject_data = _read_pyproject(name, _load_toml=_load_toml)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qflslxot\overlay\Lib\site-packages\setuptools_scm\_integration\pyproject_reading.py", line 55, in read_pyproject
      raise LookupError(f"{name} does not contain a tool.{tool_name} section") from e
  LookupError: pyproject.toml does not contain a tool.setuptools_scm section
  running AmiciInstall
  running egg_info
  writing amici.egg-info\PKG-INFO
  writing dependency_links to amici.egg-info\dependency_links.txt
  writing entry points to amici.egg-info\entry_points.txt
  writing requirements to amici.egg-info\requires.txt
  writing top-level names to amici.egg-info\top_level.txt
  ERROR setuptools_scm._file_finders.git listing git files failed - pretending there aren't any
  Traceback (most recent call last):
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qflslxot\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qflslxot\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qflslxot\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 180, in <module>
    File "<string>", line 164, in main
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qflslxot\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qflslxot\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
      return run_commands(dist)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qflslxot\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
      dist.run_commands()
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qflslxot\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qflslxot\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
      super().run_command(command)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qflslxot\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qflslxot\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 318, in run
      self.find_sources()
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qflslxot\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 326, in find_sources
      mm.run()
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qflslxot\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 548, in run
      self.add_defaults()
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qflslxot\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 589, in add_defaults
      rcfiles = list(walk_revctrl())
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qflslxot\overlay\Lib\site-packages\setuptools\command\sdist.py", line 18, in walk_revctrl
      for item in ep.load()(dirname):
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qflslxot\overlay\Lib\site-packages\setuptools_scm\_file_finders\__init__.py", line 103, in find_files
      res: list[str] = command(path)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qflslxot\overlay\Lib\site-packages\setuptools_scm\_file_finders\hg.py", line 50, in hg_find_files
      toplevel = _hg_toplevel(path)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qflslxot\overlay\Lib\site-packages\setuptools_scm\_file_finders\hg.py", line 18, in _hg_toplevel
      res = _run(
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qflslxot\overlay\Lib\site-packages\setuptools_scm\_run_cmd.py", line 138, in run
      res = subprocess.run(
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\subprocess.py", line 507, in run
      stdout, stderr = process.communicate(input, timeout=timeout)
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\subprocess.py", line 1134, in communicate
      stdout, stderr = self._communicate(input, endtime, timeout)
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\subprocess.py", line 1510, in _communicate
      raise TimeoutExpired(self.args, orig_timeout)
  subprocess.TimeoutExpired: Command '['hg', 'root']' timed out after 20 seconds
  error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
  
  See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\hostedtoolcache\windows\Python\3.9.13\x64\python.exe' 'C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\RUNNER~1\AppData\Local\Temp\tmpo_ptrtbl'
  cwd: C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-_clk25ua
  Getting requirements to build wheel: finished with status 'error'
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Error: Process completed with exit code 1.
```

**Comment by dweindl** [comment]
My current understanding is that this warning (`LookupError: pyproject.toml does not contain a tool.setuptools_scm section`) is there because `cmake-build-extension` requires `setuptools-scm`. Not much we can do about that. The warning will be shown, unless we configure setuptools-scm for amici - which we might want to do at some point - but we can't disable it easily. 

The error `  ERROR setuptools_scm._file_finders.git listing git files failed - pretending there aren't any` seems to have been just some temporary issue.

Closing.
